services:
  app:
    build: .
    image: ai-track
    container_name: intern-ai-tracker
    ports:
      - "9004:8005"
    env_file:
      - .env
    volumes:
      - app_data:/app/data
      - app_uploads:/app/uploads
      - app_outputs:/app/outputs
    restart: unless-stopped

volumes:
  app_data:
    name: intern_ai_tracker_app_data
  app_uploads:
    name: intern_ai_tracker_app_uploads
  app_outputs:
    name: intern_ai_tracker_app_outputs
